### ISSUE TITLE
Error messages are flaky

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery-playground#4]
The error positions are off:
https://media.discordapp.net/attachments/532721901886504981/566846632881029150/unknown.png

As @thangngoc89 mentioned, the error messages are relative to the beginning of a _phrase_ which is not the same as the absolute location (so the error messages are wrong).

We need to do something similar to sketch - break the file up into phrases, keep the relative location, and correct the position in the error messages. This will allow us to place diagnostics directly in the monaco editor.

Switching to a phrase-based evaluation will also open up some other improvements for the editing experience:
- We could show typing information as a 'codelens' for the phrase
- We could show compilation progress for each 'phrase' which would feel better than just waiting for the entire playground compilation.

**Comment by thangngoc89** [comment]
Related code here : https://github.com/Sketch-sh/engine/blob/27d3869aa8b4eb5fb0561570011e9a8857547797/src/engine/execute.re

**Comment by bryphe** [comment]
Thanks @thangngoc89 !

**Comment by bryphe** [comment]
Fixed with #17
